--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 30/10/2023 19:04:45
-- Server version: 5.5.5-10.1.40-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE alquiler_portatiles;

--
-- Drop table `alumnos`
--
DROP TABLE IF EXISTS alumnos;

--
-- Drop table `aplicaciones_instaladas`
--
DROP TABLE IF EXISTS aplicaciones_instaladas;

--
-- Drop table `portatiles`
--
DROP TABLE IF EXISTS portatiles;

--
-- Drop table `cargadores`
--
DROP TABLE IF EXISTS cargadores;

--
-- Drop table `ratones`
--
DROP TABLE IF EXISTS ratones;

--
-- Drop table `almacenes`
--
DROP TABLE IF EXISTS almacenes;

--
-- Set default database
--
USE alquiler_portatiles;

--
-- Create table `almacenes`
--
CREATE TABLE almacenes (
  id_almacen int(11) NOT NULL AUTO_INCREMENT,
  aula varchar(4) DEFAULT NULL,
  capacidad int(4) DEFAULT NULL,
  PRIMARY KEY (id_almacen)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `uk_aula` on table `almacenes`
--
ALTER TABLE almacenes
ADD UNIQUE INDEX uk_aula (aula);

--
-- Create table `ratones`
--
CREATE TABLE ratones (
  id_raton int(11) NOT NULL AUTO_INCREMENT,
  codigo varchar(4) DEFAULT NULL,
  marca varchar(24) DEFAULT NULL,
  modelo varchar(24) DEFAULT NULL,
  tipo_conector varchar(8) DEFAULT NULL,
  estado_alquiler varchar(24) DEFAULT NULL,
  id_almacen int(11) DEFAULT NULL,
  PRIMARY KEY (id_raton)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `uk_codigo` on table `ratones`
--
ALTER TABLE ratones
ADD UNIQUE INDEX uk_codigo (codigo);

--
-- Create foreign key
--
ALTER TABLE ratones
ADD CONSTRAINT fk_ratones_almacenes FOREIGN KEY (id_almacen)
REFERENCES almacenes (id_almacen);

--
-- Create table `cargadores`
--
CREATE TABLE cargadores (
  id_cargador int(11) NOT NULL AUTO_INCREMENT,
  codigo varchar(4) DEFAULT NULL,
  potencia int(8) DEFAULT NULL,
  estado_alquiler varchar(24) DEFAULT NULL,
  id_almacen int(11) DEFAULT NULL,
  PRIMARY KEY (id_cargador)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `uk_codigo` on table `cargadores`
--
ALTER TABLE cargadores
ADD UNIQUE INDEX uk_codigo (codigo);

--
-- Create foreign key
--
ALTER TABLE cargadores
ADD CONSTRAINT fk_cargadores_almacenes FOREIGN KEY (id_almacen)
REFERENCES almacenes (id_almacen);

--
-- Create table `portatiles`
--
CREATE TABLE portatiles (
  id_portatil int(11) NOT NULL AUTO_INCREMENT,
  codigo varchar(4) DEFAULT NULL,
  marca varchar(24) DEFAULT NULL,
  modelo varchar(24) DEFAULT NULL,
  procesador varchar(24) DEFAULT NULL,
  memoria_ram int(4) DEFAULT NULL,
  dispositivo_almacenamiento varchar(24) DEFAULT NULL,
  capacidad_almacenamiento int(8) DEFAULT NULL,
  estado_alquiler varchar(24) DEFAULT NULL,
  id_cargador int(11) DEFAULT NULL,
  id_raton int(11) DEFAULT NULL,
  id_almacen int(11) DEFAULT NULL,
  PRIMARY KEY (id_portatil)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `uk_codigo` on table `portatiles`
--
ALTER TABLE portatiles
ADD UNIQUE INDEX uk_codigo (codigo);

--
-- Create foreign key
--
ALTER TABLE portatiles
ADD CONSTRAINT fk_portatiles_almacenes FOREIGN KEY (id_almacen)
REFERENCES almacenes (id_almacen);

--
-- Create foreign key
--
ALTER TABLE portatiles
ADD CONSTRAINT fk_portatiles_cargadores FOREIGN KEY (id_cargador)
REFERENCES cargadores (id_cargador);

--
-- Create foreign key
--
ALTER TABLE portatiles
ADD CONSTRAINT fk_portatiles_ratones FOREIGN KEY (id_raton)
REFERENCES ratones (id_raton);

--
-- Create table `aplicaciones_instaladas`
--
CREATE TABLE aplicaciones_instaladas (
  id_aplicacion int(11) NOT NULL AUTO_INCREMENT,
  aplicacion varchar(32) DEFAULT NULL,
  id_portatil int(11) DEFAULT NULL,
  PRIMARY KEY (id_aplicacion)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `uk_aplicacion_portatil` on table `aplicaciones_instaladas`
--
ALTER TABLE aplicaciones_instaladas
ADD UNIQUE INDEX uk_aplicacion_portatil (aplicacion, id_portatil);

--
-- Create foreign key
--
ALTER TABLE aplicaciones_instaladas
ADD CONSTRAINT fk_aplicaciones_portatiles FOREIGN KEY (id_portatil)
REFERENCES portatiles (id_portatil);

--
-- Create table `alumnos`
--
CREATE TABLE alumnos (
  id_alumno int(11) NOT NULL AUTO_INCREMENT,
  dni varchar(8) DEFAULT NULL,
  nombre varchar(24) DEFAULT NULL,
  apellidos varchar(48) DEFAULT NULL,
  curso varchar(96) DEFAULT NULL,
  aula varchar(4) DEFAULT NULL,
  turno varchar(8) DEFAULT NULL,
  estado_matricula varchar(16) DEFAULT NULL,
  id_portatil int(11) DEFAULT NULL,
  id_cargador int(11) DEFAULT NULL,
  id_raton int(11) DEFAULT NULL,
  PRIMARY KEY (id_alumno)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `uk_dni` on table `alumnos`
--
ALTER TABLE alumnos
ADD UNIQUE INDEX uk_dni (dni);

--
-- Create foreign key
--
ALTER TABLE alumnos
ADD CONSTRAINT fk_alumnos_cargadores FOREIGN KEY (id_cargador)
REFERENCES cargadores (id_cargador);

--
-- Create foreign key
--
ALTER TABLE alumnos
ADD CONSTRAINT fk_alumnos_portatiles FOREIGN KEY (id_portatil)
REFERENCES portatiles (id_portatil);

--
-- Create foreign key
--
ALTER TABLE alumnos
ADD CONSTRAINT fk_alumnos_ratones FOREIGN KEY (id_raton)
REFERENCES ratones (id_raton);

-- 
-- Dumping data for table almacenes
--
-- Table alquiler_portatiles.almacenes does not contain any data (it is empty)

-- 
-- Dumping data for table cargadores
--
-- Table alquiler_portatiles.cargadores does not contain any data (it is empty)

-- 
-- Dumping data for table ratones
--
-- Table alquiler_portatiles.ratones does not contain any data (it is empty)

-- 
-- Dumping data for table portatiles
--
-- Table alquiler_portatiles.portatiles does not contain any data (it is empty)

-- 
-- Dumping data for table aplicaciones_instaladas
--
-- Table alquiler_portatiles.aplicaciones_instaladas does not contain any data (it is empty)

-- 
-- Dumping data for table alumnos
--
-- Table alquiler_portatiles.alumnos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;