package unidad1.ejercicios.ejercicio12_TareaFinal;

public enum Modelos {
    CAZA_ARC170, CAZA_BELBULLAB22, CAZA_ALAB, CAZA_BTL_ALAY, CAZA_Z95, CAZA_N1,
    CARGUERO_YT1300, CARGUERO_BFF1, CARGUERO_HT2200, CARGUERO_AA9,
    CAÑONERA_LAATI,
    CORBETA_CR70, CORBETA_CR90,
    CRUCERO_CARRACK, CRUCERO_ACORAZADO, CRUCERO_CONSULAR,
    DESTRUCTOR_RECUSANTE, DESTRUCTOR_PROVIDENCIA,
    FRAGATA_MUNIFICENTE,
    LANZADERA_T4A, LANZADERA_CENTINELA, LANZADERA_KAPPA,
    TRANSPORTE_GR75, TRANSPORTE_ACCION6
}
